name: Code Coverage Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and run tests
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Validate code coverage
        run: |
          # Extract the coverage percentage from the generated report
          coverage=$(cat TestResults/coverage.cobertura.xml | grep -oP '(?<=<LineRate>)[^<]+')

          # Convert coverage percentage to numeric value
          coverage_percentage=$(awk "BEGIN {print $coverage * 100}")

          # Check if coverage percentage is below the threshold
          if (( $(echo "$coverage_percentage < 80" | bc -l) )); then
            echo "Code coverage is below the threshold (80%). Coverage percentage: $coverage_percentage%"
            exit 1
          fi
          
      - name: Exclude Program class from coverage
        run: |
          echo "-[Namespace].Program" >> coverlet.exclude
